# Generated by Django 4.0.2 on 2022-02-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialRecommender', '0002_todo_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(default='computer', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
