# Generated by Django 4.0.2 on 2022-03-03 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialRecommender', '0006_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
