# Generated by Django 4.0.2 on 2022-03-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialRecommender', '0008_alter_note_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('subject', models.TextField()),
            ],
        ),
    ]
