# Generated by Django 4.0 on 2022-03-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialRecommender', '0010_material_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='document',
        ),
    ]
