# Generated by Django 4.0 on 2022-03-11 18:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialRecommender', '0011_remove_material_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
