# Generated by Django 4.0 on 2022-03-11 18:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialRecommender', '0012_alter_material_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='categorise',
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
