# Generated by Django 4.0 on 2022-03-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialRecommender', '0013_remove_material_categorise_alter_material_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='categorise',
            field=models.CharField(choices=[('Cryptography', 'Cryptography'), ('Digital Logics', 'Digital Logics')], default='Cryptography', max_length=70),
        ),
    ]
