# Generated by Django 4.0 on 2022-03-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialRecommender', '0014_material_categorise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='categorise',
            field=models.CharField(max_length=70),
        ),
    ]
