# Generated by Django 4.0 on 2022-03-12 01:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialRecommender', '0017_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
