# Generated by Django 4.0 on 2022-03-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialRecommender', '0022_new_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_User',
        ),
    ]
